project:
  type: book
  output-dir: docs
language: jayy.yml
  
book: 
  title: "KUT 統計学2"
  author: "矢内 勇生"
  date: "March 22, 2022"
  sidebar: 
    style: docked
    background: light
  page-navigation: true
  page-footer: 
    center: "Copyright 2022-2023, Yuki Yanai"
    background: light
    border: false
  search: true
  site-url: https://yukiyanai.github.io/stat2/
  repo-url: https://github.com/yukiyanai/stat2/
  repo-branch: main
  sharing: [twitter, facebook]
  chapters: 
    - index.qmd
    - how2quarto.qmd
    - rng.qmd
    - clt.qmd
    - intro-to-inference.qmd
    - pop-n-sample.qmd
    - lawoflargenumbers.qmd
    - sampling-distribution.qmd
    - estimating-mean.qmd
    - t-distribution.qmd
    - mean-comparison.qmd
    - bivariate.qmd
    
format:
  html:
    theme: yeti
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: arrow
    html-math-method: mathjax
    code-link: true
    fig-width: 5
    fig-height: 4
    link-external-newwindow: true

crossref:
  ref-hyperlink: true
