project:
  type: book
  output-dir: docs
editor: source
lang: ja
language: jayy.yml
  
book: 
  title: "KUT 統計学2"
  author: "矢内 勇生"
  sidebar: 
    style: docked
    background: light
  page-navigation: true
  page-footer: 
    center: "Copyright 2022, Yuki Yanai"
    background: light
    border: false
  search: true
  repo-url: https://yukiyanai.github.io/statistics/
  sharing: [twitter, facebook]
  chapters: 
    - index.qmd
    - intro-to-R.qmd
    - intro-to-RStudio.qmd
    - descriptive-stat.qmd
    - r-markdown.qmd
    - intro-to-ggplot2.qmd
    - rng.qmd
    - clt.qmd
    - intro-to-inference.qmd
    - pop-n-sample.qmd
    - lawoflargenumbers.qmd
    - sampling-distribution.qmd
    - estimating-mean.qmd
    - t-distribution.qmd
    - mean-comparison.qmd
  
    
format:
  html:
    theme: yeti
    number-sections: true
    highlight-style: arrow
    html-math-method: mathjax
    code-link: true
    fig-width: 5
    fig-height: 4
    filters:
      - add-target-attr.lua

crossref:
  ref-hyperlink: true
  

